### ISSUE TITLE
Domácí úkoly z 8. lekce

### ISSUE THREAD

**Issue by katroska** [katroska/python-032021#1]
Ahoj @pesikj,
prosím o kontrolu domácích úkolů z 8. lekce.
Předem děkuji,
Katka

**Comment by katroska** [comment]
Omlouvám se, až teď jsem si všimla, že jsem je zatím nedodělala... Tyhle zatím nemá smysl kontrolovat :)

**Comment by pesikj** [comment]
Ahoj Katko, ale klidně to dodělej i po termínu :-)
J.
